"""verify_e8_weyl_orbit.py -- independent Python/Fraction mirror of
e8_weyl_orbit_unification.lean (generated by Aristotle/Harmonic, Lean 4 +
Mathlib, `native_decide`/`decide +kernel` -- machine-checked but external
to this repo's own verification chain until reproduced here).

Same "mirror before trusting" discipline this project applies to its own
NumPy-vs-PyTorch layers, applied to an external formal-verification
artifact: exact rational arithmetic (fractions.Fraction, matching Lean's
ℚ exactly -- no floating point anywhere in this file) re-derives the
Lean file's three theorems independently.

What the Lean file claims (its own docstring): the "six canonical
P-vectors" -- six pairs (P_i, Q_i) of two-blade sedenion elements -- map
to five distinct 8-dimensional vectors (v1..v5, all norm^2 = 2, i.e. E8
roots) that all lie in a single E8 Weyl orbit (all reduce to the same
dominant weight lambda under explicit reflection sequences), with one
antipodal pair (v2 = -v3) connected by a single simple reflection.

This script separately verifies:
  [A] the six (P_i, Q_i) pairs are genuine bilateral zero divisors under
      THIS repo's own sedenion_kernel.cd_mult (Baez convention) -- done
      already in the interactive session; P2/Q2 == this project's own
      ZD_PAIR (e3+e12, e5+e10).
  [B] Theorem 1a: norm_sq(v1..v5) == 2 for all five.
  [C] Theorem 1b: v2 + v3 == 0, and the simple reflection s_alpha4 maps
      v2 to v3.
  [D] Theorem 1c: each of the five reduction sequences reduces its
      vector to the same target_lambda.

Note what this script does NOT establish: the mapping from the 16-
dimensional sedenion pairs (P_i, Q_i) to the 8-dimensional vectors
v1..v5 is not given in the Lean file itself (v1..v5 are defined directly
by their coordinates, not derived from P_i/Q_i by any formula in that
file) -- that derivation, if it exists, lives outside this file. This
script verifies the E8/Weyl claims about v1..v5 exactly as given, and
separately verifies the P_i/Q_i pairs are real zero divisors; it does
NOT verify a P_i/Q_i -> v_i correspondence, because the Lean file
doesn't state one to check.

Run:  zda-env\\Scripts\\python.exe verify_e8_weyl_orbit.py
"""
from fractions import Fraction as Fr

# ---------------------------------------------------------------
# [A] bilateral zero divisors (repeats the interactive check, kept here
# so this script is a standalone, rerunnable record)
# ---------------------------------------------------------------
import numpy as np
from sedenion_kernel import cd_mult

def elt16(*terms):
    v = np.zeros(16)
    for (i, s) in terms:
        v[i] = s
    return v

PQ_PAIRS = {
    "P1,Q1": (elt16((1, 1), (14, 1)), elt16((3, 1), (12, 1))),
    "P2,Q2": (elt16((3, 1), (12, 1)), elt16((5, 1), (10, 1))),
    "P3,Q3": (elt16((4, 1), (11, 1)), elt16((6, 1), (9, 1))),
    "P4,Q4": (elt16((1, 1), (14, -1)), elt16((3, 1), (12, -1))),
    "P5,Q5": (elt16((1, 1), (14, -1)), elt16((5, 1), (10, 1))),
    "P6,Q6": (elt16((2, 1), (13, -1)), elt16((6, 1), (9, 1))),
}

print("[A] bilateral zero-divisor check (repo cd_mult, Baez convention):")
all_zd = True
for name, (P, Q) in PQ_PAIRS.items():
    pq, qp = cd_mult(P, Q), cd_mult(Q, P)
    ok = np.abs(pq).max() < 1e-12 and np.abs(qp).max() < 1e-12
    all_zd &= ok
    print(f"    {name}: PQ=QP=0: {ok}")
assert all_zd
zd_pair_match = np.array_equal(PQ_PAIRS["P2,Q2"][0], elt16((3, 1), (12, 1))) and \
                np.array_equal(PQ_PAIRS["P2,Q2"][1], elt16((5, 1), (10, 1)))
print(f"    P2,Q2 == project ZD_PAIR (e3+e12, e5+e10): {zd_pair_match}\n")
assert zd_pair_match

# ---------------------------------------------------------------
# [B-D] E8 Weyl orbit, exact rationals (fractions.Fraction, mirrors Lean's ℚ)
# ---------------------------------------------------------------
V8 = tuple  # 8-tuple of Fraction

def mk(*xs):
    assert len(xs) == 8
    return tuple(Fr(x) for x in xs)

def dot(u, v):
    return sum(u[i] * v[i] for i in range(8))

def norm_sq(v):
    return dot(v, v)

def s(alpha, v):
    """Weyl reflection: v - 2(v.alpha)/(alpha.alpha) * alpha"""
    c = Fr(2) * dot(v, alpha) / dot(alpha, alpha)
    return tuple(v[i] - c * alpha[i] for i in range(8))

def vsub(u, v):
    return tuple(u[i] - v[i] for i in range(8))

def vadd(u, v):
    return tuple(u[i] + v[i] for i in range(8))

# transcribed verbatim from e8_weyl_orbit_unification.lean
v1 = mk(0, 1, 0, 0, 0, 0, -1, 0)
v2 = mk(0, 0, 0, 1, -1, 0, 0, 0)
v3 = mk(0, 0, 0, -1, 1, 0, 0, 0)
v4 = mk(0, 1, 0, 0, 0, 0, 1, 0)
v5 = mk(0, 0, 1, 0, 0, 1, 0, 0)

alpha1 = mk(1, -1, 0, 0, 0, 0, 0, 0)
alpha2 = mk(0, 1, -1, 0, 0, 0, 0, 0)
alpha3 = mk(0, 0, 1, -1, 0, 0, 0, 0)
alpha4 = mk(0, 0, 0, 1, -1, 0, 0, 0)
alpha5 = mk(0, 0, 0, 0, 1, -1, 0, 0)
alpha6 = mk(0, 0, 0, 0, 0, 1, 1, 0)
alpha7 = mk(*([Fr(-1, 2)] * 8))
alpha8 = mk(0, 0, 0, 0, 0, 1, -1, 0)

roots = {1: alpha1, 2: alpha2, 3: alpha3, 4: alpha4,
         5: alpha5, 6: alpha6, 7: alpha7, 8: alpha8}

target_lambda = mk(1, 0, 0, 0, 0, 0, 0, -1)

def apply_seq(v, seq):
    for k in seq:
        v = s(roots[k], v)
    return v

seq1 = [1,6,5,4,3,2,7,6,5,4,3,8,5,4,6,5,7,6,8,5,4,3,2,1]
seq2 = [3,2,1,5,6,7,8,5,4,3,2,6,5,4,3,8,5,4,6,5,7,6,8,5,4,3,2,1]
seq3 = [4,3,2,1,5,6,7,8,5,4,3,2,6,5,4,3,8,5,4,6,5,7,6,8,5,4,3,2,1]
seq4 = [1,7,8,5,4,3,2,6,5,4,3,8,5,4,6,5,7,6,8,5,4,3,2,1]
seq5 = [2,1,5,4,3,2,7,6,5,4,3,8,5,4,6,5,7,6,8,5,4,3,2,1]

print("[B] Theorem 1a (all five have squared norm 2, i.e. are E8 roots):")
for name, v in [("v1", v1), ("v2", v2), ("v3", v3), ("v4", v4), ("v5", v5)]:
    n2 = norm_sq(v)
    print(f"    norm_sq({name}) = {n2}  (== 2: {n2 == 2})")
    assert n2 == 2

print("\n[C] Theorem 1b (antipodal pair, single-reflection link):")
antipodal = vadd(v2, v3) == mk(0,0,0,0,0,0,0,0)
reflected = s(alpha4, v2) == v3
print(f"    v2 + v3 == 0: {antipodal}")
print(f"    s(alpha4, v2) == v3: {reflected}")
assert antipodal and reflected

print("\n[D] Theorem 1c (single Weyl orbit -- all reduce to target_lambda):")
for name, v, seq in [("v1", v1, seq1), ("v2", v2, seq2), ("v3", v3, seq3),
                      ("v4", v4, seq4), ("v5", v5, seq5)]:
    reduced = apply_seq(v, seq)
    ok = reduced == target_lambda
    print(f"    {name} -> {reduced}  (== target_lambda: {ok})")
    assert ok

print("\nAll Lean-file theorems independently reproduced in exact rational "
      "arithmetic (fractions.Fraction), no floating point anywhere.")
